version: "3"
services: 
  db:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: estoque_db_1
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
         - 8081:5432/tcp
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
